apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name | trunc 55 }}-app-pdb
spec:
  minAvailable: {{ .Values.app.minAvailable }}
  selector:
    matchLabels:
      component: app
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
