apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name | trunc 50   }}-db-conn-info
  labels:
    component: app-secret
    {{- include "infra-interview-test.labels" . | nindent 4}}
type: Opaque
stringData:
  TYPEORM_CONNECTION: {{ .Values.database.type }}
  TYPEORM_HOST: {{ .Release.Name | trunc 56 }}-db-svc
  {{- if or (eq .Values.database.type "mariadb") (eq .Values.database.type "mysql") }}
  TYPEORM_PORT: "3306"
  {{- else if eq .Values.database.type "postgresql" }}
  TYPEORM_PORT: "5432"
  {{- end }}
  TYPEORM_USERNAME: {{ .Values.app.database.name | trim | trunc 28 }}-app
  TYPEORM_PASSWORD: {{ .Values.app.database.password | trim | trunc 79 }}
  TYPEORM_DATABASE: {{ .Values.app.database.name | trunc 64 }}
  TYPEORM_SYNCHRONIZE: "true"
  TYPEORM_ENTITIES: "src/entity/*.js"
  TYPEORM_SUBSCRIBERS: "src/subscriber/*.js"
  TYPEORM_MIGRATIONS: "src/migration/*.js"
  TYPEORM_ENTITIES_DIR: "src/entity"
  TYPEORM_MIGRATIONS_DIR: "src/migration"
  TYPEORM_SUBSCRIBERS_DIR: "src/subscriber"
