{{- if .Values.app.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name | trunc 55   }}-app-hpa
  labels:
    component: app-hpa
    {{- include "infra-interview-test.labels" . | nindent 4}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name | trunc 59   }}-app
  minReplicas: {{ .Values.app.hpa.minReplicas }}
  maxReplicas: {{ .Values.app.hpa.maxReplicas }}
  metrics:
  {{- .Values.app.hpa.metrics | toYaml | nindent 2 }}
  behavior:
  {{- .Values.app.hpa.behavior | toYaml | nindent 4 }}
{{- end }}
