apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name | trunc 46   }}-app-init-scripts
  labels:
    component: app-configmap
    {{- include "infra-interview-test.labels" . | nindent 4}}
data:
  wait-db.sh: |
    while true; do
      {{- if or (eq .Values.database.type "mariadb") (eq .Values.database.type "mysql") }}
      mysql -h $DB_HOST -p$DB_PASSWORD -u root -e "USE mysql;" 2>/dev/null
      {{- else if eq .Values.database.type "postgresql" }}
      psql -h $DB_HOST -d $DB_NAME -c "SELECT 1;" > /dev/null 2>&1
      {{- end }}

      if [ $? -eq 0 ]; then
          echo "Database is ready!"
          break
      else
          echo "Waiting for database be ready..."
          sleep 5
      fi
    done
