apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name | trunc 55   }}-db-info
  labels:
    component: database-secret
    {{- include "infra-interview-test.labels" . | nindent 4}}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.database.rootPassword | trim | trunc 79 }}
