{{- if .Values.webserver.enabled  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name | trunc 46   }}-webserver-config
  labels:
    component: webserver-configmap
    {{- include "infra-interview-test.labels" . | nindent 4}}
data:
  default.conf: |
    server {
      listen       {{ .Values.webserver.port }};
      access_log   /var/log/nginx/access.log;
      error_log    /var/log/nginx/error.log;

      location / {
        proxy_pass http://{{ .Release.Name | trunc 55 }}-app-svc:{{ .Values.app.port }};
      }
    }
{{- end }}
