app:
  image: talessrc/private-infrastructure-interview-app:1.0.0
  port: 3000
  replicas: 1
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: "0.2"
      memory: 80Mi
    limits:
      cpu: "0.5"
      memory: 150Mi
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 180


database:
  type: mariadb
  image: mariadb:5.5
  dbName: interview
  service:
    type: ClusterIP
  user:
    name: root
    password: testpassword

webserver:
  enabled: true
  image: nginx:1.25.3-alpine
  port: 80
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: "0.05"
      memory: 50Mi
    limits:
      cpu: "0.15"
      memory: 300Mi
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 180

ingress:
  enabled: true
  annotations:
  hosts:
  - name: localhost
  - name: interview.local
  tls: []
  # - secretName: interview-app-tls
  #   hosts:
  #   - interview.local

imagePullSecret:
  # registry: https://index.docker.io/v1/
  # username: <your-username>
  # password: <your-password>

networkPolicy:
  allowIngressOnlyWithinNamespace: true
