app:
  image: talessrc/infrastructure-interview-app:1.0.0
  port: 3000
  replicas: 1
  imagePullPolicy: Always
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: "0.2"
      memory: 80Mi
    limits:
      cpu: "0.5"
      memory: 150Mi
  livenessProbe:
    httpGetPath: /posts
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 2
  readinessProbe:
    httpGetPath: /posts
    initialDelaySeconds: 15
    periodSeconds: 5
    timeoutSeconds: 2
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 180
  securityContext:
    runAsUser: 100

database:
  type: mariadb
  image: mariadb:5.5
  dbName: interview
  service:
    type: ClusterIP
  user:
    name: root
    password: testpassword
  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  securityContext:
    runAsUser: 999

webserver:
  enabled: true
  image: nginx:1.25.3-alpine
  port: 80
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: "0.05"
      memory: 50Mi
    limits:
      cpu: "0.15"
      memory: 300Mi
  livenessProbe:
    httpGetPath: /posts
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
  readinessProbe:
    httpGetPath: /posts
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 180
  securityContext:
    runAsUser: 0

ingress:
  enabled: true
  annotations:
  hosts:
  - name: localhost
  - name: interview.local
  tls: []
  # - secretName: interview-app-tls
  #   hosts:
  #   - interview.local

imagePullSecret:
  # registry: https://index.docker.io/v1/
  # username: <your-username>
  # password: <your-password>

networkPolicy:
  allowIngressOnlyWithinNamespace: true
